# Generated by Django 2.2.2 on 2019-06-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
