# Generated by Django 2.2.2 on 2019-06-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_delete_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
